service: ae-scheduling-service

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128
  timeout: 10
  stage: production
  region: eu-west-3

functions:
  api:
    handler: lambda.universal
    events:
      - http: ANY {proxy+}
      - http: ANY /
